apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      env: dev
  template:
    metadata:
      labels:
        app: grafana
        env: dev
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pasword"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
    env: dev
  type: ClusterIP
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traitor-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: grafana.traitor.ar
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
  tls:
    - hosts:
        - grafana.traitor.ar
      secretName: traitor-cert
