apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
  selector:
    app: prometheus
    tier: frontend
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        tier: frontend
    spec:
      containers:
        - image: prom/prometheus
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          name: prometheus
          ports:
            - containerPort: 9090
              name: prometheus
          volumeMounts:
            - name: config-storage
              mountPath: /etc/prometheus
      volumes:
        - name: config-storage
          configMap:
            name: config
